AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for sam-webshell

Globals:
  Function:
    Timeout: 10
    MemorySize: 128
    Handler: app.lambda_handler
    Runtime: python3.11

Resources:
  DocumentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: documents/
      Environment:
        Variables:
          TEMPLATE_BUCKET_NAME: !Sub "${AWS::StackName}-templates"
          GENERATED_DOCUMENTS_BUCKET_NAME: !Sub "${AWS::StackName}-generated-documents"
      Policies:
        # TODO: narrower policies
        # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-template-list.html
        # - AmazonS3FullAccess:
        #     BucketName: !Ref GeneratedDocumentsBucket
        - AWSLambdaBasicExecutionRole
        - AmazonS3FullAccess
      Events:
        GetDocuments:
          Type: Api
          Properties:
            Path: /documents
            Method: get
        CreateDocument:
          Type: Api
          Properties:
            Path: /documents
            Method: post

  TemplatesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-templates"

  GeneratedDocumentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}-generated-documents"

Outputs:
  RestApi:
    Description: API Gateway endpoint URL for Prod stage (implicit)
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
  DocumentsFunction:
    Description: Documents Function ARN
    Value: !GetAtt DocumentsFunction.Arn
  DocumentsFunctionIamRole:
    Description: Implict role for Documents Function
    Value: !GetAtt DocumentsFunctionRole.Arn
  TemplatesBucket:
    Description: Bucket for template documents and emails
    Value: !GetAtt  TemplatesBucket.Arn
  GeneratedDocumentsBucket:
    Description: Bucket for generated documents and emails
    Value: !GetAtt  GeneratedDocumentsBucket.Arn