AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for sam-webshell

Parameters:
 TemplatesBucketName:
  Type: String

Globals:
  Function:
    Timeout: 10
    MemorySize: 128
    Handler: app.lambda_handler
    Runtime: python3.11

Resources:
  DocumentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: documents/
      Events:
        GetDocuments:
          Type: Api
          Properties:
            Path: /documents
            Method: get

  TemplatesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref TemplatesBucketName


Outputs:
  RestApi:
    Description: API Gateway endpoint URL for Prod stage (implicit)
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
  DocumentsFunction:
    Description: Documents Function ARN
    Value: !GetAtt DocumentsFunction.Arn
  DocumentsFunctionIamRole:
    Description: Implict role for Documents Function
    Value: !GetAtt DocumentsFunctionRole.Arn
  TemplatesBucketName:
    Description: Bucket for template documents and emails
    Value: !GetAtt  TemplatesBucket.Arn